---
title: "Exploratory Analysis"
author: "Reece Carmody"
date: "2025-11-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)

data = read.csv("RWAR_turb_cond_counts_pH_temp.csv")

data$Timestamp = mdy_hm(data$Timestamp)

# Trying to determine what rows have outliers.
# The goal is to go by column, remove outliers & average that day's data, then ultimately combine every column after it's cleaned to create our fully cleaned data frame.
# Then combine with alkalinity and hardness & coagulant doses data??

ggplot(data, aes(x = Timestamp, y = Turbidity..NTU)) +
  geom_point()

data[data$Turbidity..NTU > 10, ] # row 2701 and 5446

ggplot(data, aes(x = Timestamp, y = Conductivity..mS.cm.1)) +
  geom_point()

data[data$Conductivity..mS.cm.1 > 15, ] # row 5270

# Not sure what to do with particle count (PC) data just yet

ggplot(data, aes(x = Timestamp, y = pH..SU)) +
  geom_point()

ggplot(data, aes(x = Timestamp, y = Temperature..deg.C)) +
  geom_point()

```