---
title: "Exploratory Analysis Ethan Schilling"
output: html_document
---


```{r}
library(tidyverse)
library(knitr)
library(tidymodels)
library(dplyr)
```

```{r}

TDS_unfilt <- read_csv("RWAR_TDS.csv")
TOC_unfilt <- read_csv("RWAR_TOC.csv")

df_TDS <- TDS_unfilt %>%
  rename(date = 1, value = 2) %>%
  mutate(date = as.Date(date, format = "%d-%b-%y"))

TDS_plot <- ggplot(df_TDS, aes(x = date, y = value)) +
  geom_line() +
  labs(x = "Date", y = "TDS Value", title = "TDS over Time")

saveRDS(TDS_plot,"TDS_plot.rds")


df_TOC <- TOC_unfilt %>% 
  rename(date = 1, value = 2) %>%
  mutate(date = as.Date(date, format = "%d-%b-%y"))
  
TOC_plot <- ggplot(df_TOC, aes(x = date, y = value)) +
  geom_line() +
  labs(x = "Date", y = "TOC Value", title = "TOC over Time")


saveRDS(TOC_plot,"TOC_plot.rds")

```



```{r}
library(ggplot2)
library(tidyr)
library(dplyr)

dosing_data <- read_csv("RWAR_dosing_cleaned.csv")



dosing_long <- dosing_data %>%
  pivot_longer(
    cols = starts_with("mean_"),
    names_to = "Characteristics",
    values_to = "Value"
  )

ggplot(dosing_long, aes(x = Timestamp, y = Value, color = Ferric.chloride..mg.L)) +
  geom_point(size = 0.7) +
  facet_wrap(~Characteristics, scales = "free_y") +
  scale_color_viridis_c(option = "plasma") +
  theme_minimal() +
  labs(
    x = "Date",
    y = "Value",
    color = "Ferric Chloride (mg/L)",
    title = "Water Quality Characteristics Over Time by Dosing"
  )
```


