---
title: "Exploratory Analysis Ethan Schilling"
output: html_document
---


```{r}
library(tidyverse)
library(knitr)
library(tidymodels)
library(dplyr)
library(Metrics)
library(kableExtra)
```

```{r}

TDS_unfilt <- read_csv("~/DSCI445/project-4/RWAR_TDS.csv")
TOC_unfilt <- read_csv("~/DSCI445/project-4/RWAR_TOC.csv")
DOC_unfilt <- read_csv("~/DSCI445/project-4/RWAR_DOC.csv")

df_TDS <- TDS_unfilt %>%
  rename(date = 1, value = 2) %>%
  mutate(date = as.Date(date, format = "%d-%b-%y"))

TDS_plot <- ggplot(df_TDS, aes(x = date, y = value)) +
  geom_line() +
  labs(x = "Date", y = "Total Dissolved Solids mg/L", title = "Total Dissolved Solids over Time")


df_TOC <- TOC_unfilt %>% 
  rename(date = 1, value = 2) %>%
  mutate(date = as.Date(date, format = "%d-%b-%y"))
  
TOC_plot <- ggplot(df_TOC, aes(x = date, y = value)) +
  geom_line() +
  labs(x = "Date", y = "Total Organinc Carbon mg/L", title = "Total Organic Carbon over Time")

df_DOC <- DOC_unfilt %>%
  rename(date = 1, value = 2) %>%
  mutate(date = as.Date(date, format = "%d-%b-%y"))


DOC_plot <- ggplot(df_DOC, aes(x = date, y = value)) +
  geom_line() +
  labs(x = "Date", y = "Dissolved Organic Carbon mg/L", title = "Dissolved Organic Carbon over Time")


#saveRDS(TDS_plot,"TDS_plot.rds")
#saveRDS(TOC_plot,"TOC_plot.rds")
#saveRDS(DOC_plot,"DOC_plot.rds")

TDS_plot
TOC_plot
DOC_plot


```



```{r}
library(lubridate)
library(dplyr)
library(ggplot2)
library(tidyr)
library(Metrics)


dosing_data <- read.csv("~/DSCI445/project-4/RWAR_dosing_cleaned.csv")



dosing_long <- dosing_data %>%
  pivot_longer(
    cols = starts_with("mean_"),
    names_to = "Characteristics",
    values_to = "Value"
  )

ggplot(dosing_long, aes(x = Timestamp, y = Value, color = Ferric.chloride..mg.L)) +
  geom_point(size = 0.7) +
  facet_wrap(~Characteristics, scales = "free_y") +
  scale_color_viridis_c(option = "plasma") +
  theme_minimal() +
  labs(
    x = "Date",
    y = "Value",
    color = "Ferric Chloride (mg/L)",
    title = "Water Quality Characteristics Over Time by Dosing"
  )



RWAR_dosing <- read.csv("~/DSCI445/project-4/RWAR_dosing_lag_incdec.csv")

RWAR_dosing


RWAR_dosing <- RWAR_dosing %>% 
  mutate(Timestamp = ymd(Timestamp),
         Year = year(Timestamp))

RWAR_dosing


train <- RWAR_dosing %>% filter(Year %in% c(2018, 2019))
test  <- RWAR_dosing %>% filter(Year == 2020)


# All predictors

model0 <- lm(FeCl_dose ~ mean_Temp + mean_pH + mean_Conductivity + mean_Turbidity + Temp_lag1 + Temp_lag2 + pH_lag1 + pH_lag2 + Cond_lag1 + Cond_lag2 + Turb_lag1 + Turb_lag2, data = train)

test$pred_model0 <- predict(model0, newdata = test)

cat("Model 0 RMSE:", rmse(test$FeCl_dose, test$pred_model0), "\n")
cat("Model 0 MAE :", mae(test$FeCl_dose, test$pred_model0), "\n")



# 1 Interaction Term

model1 <- lm(FeCl_dose ~ mean_Temp * mean_pH + mean_Turbidity + Temp_lag1 + Turb_lag1, 
             data = train)
summary(model1)


test$pred_model1 <- predict(model1, newdata = test)

cat("Model 1 RMSE:", rmse(test$FeCl_dose, test$pred_model1), "\n")
cat("Model 1 MAE :", mae(test$FeCl_dose, test$pred_model1), "\n")

    

# 2 Interaction Terms

model2 <- lm(FeCl_dose ~ mean_Temp * mean_pH + mean_Conductivity * mean_Turbidity + Temp_lag1 + Temp_lag2 + pH_lag1 + pH_lag2, data = train)

test$pred_model2 <- predict(model2, newdata = test)

cat("Model 2 RMSE:", rmse(test$FeCl_dose, test$pred_model2), "\n")
cat("Model 2 MAE :", mae(test$FeCl_dose, test$pred_model2), "\n")


model3 <- lm(FeCl_dose ~ mean_Temp * mean_Conductivity + Temp_lag1 + Temp_lag2 + pH_lag1 + pH_lag2, data = train)

test$pred_model3 <- predict(model3, newdata = test)

cat("Model 3 RMSE:", rmse(test$FeCl_dose, test$pred_model3), "\n")
cat("Model 3 MAE :", mae(test$FeCl_dose, test$pred_model3), "\n")

# 2 Interactions: Cond and PH and Temp and Cond

model4 <- lm(FeCl_dose ~ mean_Conductivity * mean_pH + mean_Temp * mean_Conductivity + Temp_lag1 + Temp_lag2 + pH_lag1 + pH_lag2, data = train)

test$pred_model4 <- predict(model4, newdata = test)

cat("Model 4 RMSE:", rmse(test$FeCl_dose, test$pred_model4), "\n")
cat("Model 4 MAE :", mae(test$FeCl_dose, test$pred_model4), "\n")


model_descriptions <- c(
  "Main effects only",
  "Temp × pH interaction",
  "Temp × pH + Cond × Turb interactions",
  "Temp × Cond interaction",
  "Cond × pH + Temp × Cond interactions"
)

results <- data.frame(
  Model = paste0("Model ", 0:4),
  RMSE = c(
    rmse(test$FeCl_dose, test$pred_model0),
    rmse(test$FeCl_dose, test$pred_model1),
    rmse(test$FeCl_dose, test$pred_model2),
    rmse(test$FeCl_dose, test$pred_model3),
    rmse(test$FeCl_dose, test$pred_model4)
  ),
  MAE = c(
    mae(test$FeCl_dose, test$pred_model0),
    mae(test$FeCl_dose, test$pred_model1),
    mae(test$FeCl_dose, test$pred_model2),
    mae(test$FeCl_dose, test$pred_model3),
    mae(test$FeCl_dose, test$pred_model4)
  ),
  Description = model_descriptions
)


results <- results %>%
  mutate(
    RMSE = round(RMSE, 3),
    MAE  = round(MAE, 3)
  ) %>%
  arrange(RMSE)



best_rmse <- min(results$RMSE)
best_mae  <- min(results$MAE)
 

results %>%
  kable("html", caption = "Model Performance Summary ") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed"),
    full_width = FALSE,
    position = "center"
  ) %>%
  column_spec(1, bold = TRUE) %>%
  column_spec(4, width = "20em") %>%
  row_spec(which(results$RMSE == best_rmse), background = "#d4edda") %>%  
  row_spec(which(results$MAE == best_mae), background = "#cfe2f3")  

```

