---
title: "Exploratory_Analysis_Josh_Tobey"
author: "Joshua Tobey"
date: "2025-11-17"
output: html_document
---
```{r}
install.packages(c("usethis", "gitcreds"))
```

```{r}
library(tidyverse)
library(tidymodels)
library(dplyr)
library(knitr)
library(lubridate)

```

```{r}
exploratory_df <- read_csv("RWAR_dosing_cleaned.csv")
colnames(exploratory_df)
```

```{r}
ggplot(exploratory_df) +
  geom_point(aes(x = mean_Turbidity,
                 y = mean_Temp,
                 color = mean_Temp)) +
  scale_color_gradient(low = 'yellow', high = 'green')
```

```{r}
head(exploratory_df)

```


```{r}
exploratory_df$Timestamp = ymd(exploratory_df$Timestamp)
exploratory_df <- exploratory_df[order(exploratory_df$Timestamp), ]
ggplot(exploratory_df, aes(x = Timestamp,
                           y = mean_pH,
                           color = mean_pH)) +
  geom_line() + 
  scale_color_gradient(low = 'blue', high = 'red')

```

```{r}
library(patchwork)
plot1 <- ggplot(exploratory_df, aes(x = Timestamp,
                           y = mean_pH,
                           color = mean_pH)) +
  geom_line() + 
  scale_color_gradient(low = 'blue', high = 'red') +
  theme_minimal() +
  ggtitle("Average pH over Time")

plot2 <- ggplot(exploratory_df, aes(x = Timestamp,
                           y = Cationic.Polimer..mg.L,
                           color = Cationic.Polimer..mg.L)) +
  geom_line() + 
  scale_color_gradient(low = 'yellow', high = 'green') +
  theme_minimal() +
  ggtitle("Polymer Coagulant over Time")

plot1/plot2
```



```{r}
ggplot(exploratory_df) +
  geom_jitter(aes(x = mean_Turbidity,
                 y = mean_Conductivity,
                 color = mean_Conductivity), width = 1, height = 3) +
  scale_color_gradient(low = 'skyblue', high = 'orange')

```
Nothing of real interest here.
```{r}
coag_dose_df <- read_csv("CoagulantDoses_2017-20.csv")
head(coag_dose_df)

```
```{r}
#exploratory_df <- exploratory_df %>%
  #mutate(`dosing (exploratory)` = coag_dose_df$`Cationic Polimer, mg/L` )
length(exploratory_df) == length(coag_dose_df)
```
```{r}

coag_dose_df$Date <- mdy(coag_dose_df$Date)
ggplot(coag_dose_df) +
  geom_line(aes(x = Date,
                y = `Cationic Polimer, mg/L`))

```
```{r}
alk_df <- read_csv("alkalinity_hardness_cleaned.csv")
head(alk_df)

```
```{r}
alk_df$Date <- mdy(alk_df$Date)
ggplot(alk_df) +
  geom_line(aes(x = Date,
                y = alkalinity),
            color = 'orange') +
  geom_line(aes(x = Date,
                y = hardness),
            color = 'blue')
  
```
```{r}
generic_mlr <- linear_reg() |>
  set_mode("regression") |>
  set_engine("lm")

mlr_recipe <- recipe(alkalinity ~ hardness, data = alk_df)
mlr_wf <- workflow() |> 
  add_model(generic_mlr) |> 
  add_recipe(mlr_recipe)
fit(mlr_wf, data = alk_df)
```

```{r, eval = FALSE}
weekly_log_spec <- logistic_reg()
weekly_log_fit <- weekly_log_spec |>
  fit(Direction ~ Lag1 + 
      Lag2, 
      family = "binomial", 
      data = Weekly)
weekly_log_fit |>
  pluck("fit") |>
  summary()


```

```{r, eval = FALSE}
cross_validation <- initial_split(exploratory_df, prop = 0.6)
exploratory_train <- training(cross_validation)
exploratory_test <- testing(cross_validation)
#OPTION 1:
linear_recipe <- recipe(`pH SU` ~ `Temperature deg C`, data = exploratory_df)
quad_recipe <- linear_recipe |> step_mutate(`Temperature deg C_2` = `Temperature deg C`^2)
cubic_recipe <- quad_recipe |> step_mutate(`Temperature deg C_3` = `Temperature deg C`^3)
quart_recipe <- cubic_recipe |> step_mutate(`Temperature deg C_4` = `Temperature deg C`^4)
#OPTION 2:
linear_recipe <- recipe(`pH SU` ~ ., data = exploratory_df)
quad_recipe <- linear_recipe |> step_poly(all_numeric_predictors(), degree = 2)
cubic_recipe <- quad_recipe |> step_poly(all_numeric_predictors(), degree = 3)
quart_recipe <- cubic_recipe |> step_poly(all_numeric_predictors(), degree = 4)

loocv_df <- loo_cv(dfi)
test_errors <- data.frame()

retrieve_test_error <- function(least_sqrs_model, testing_set) {
  augment(least_sqrs_model, new_data = testing_set) |>
    mutate(resid2 = .resid^2) |> 
    summarise(rmse = sqrt(mean(resid2))) |>
    pull(rmse)
}

for (i in seq_len(nrow(loocv_df))) {
  train_data = training(loocv_df[i,]$splits[[1]])
  test_data = testing(loocv_df[i,]$splits[[1]])
  
  Y1 <- workflow() |> add_model(lstSqrs_spec) |> add_recipe(linear_recipe) |> fit(train_data)
  Y2 <- workflow() |> add_model(lstSqrs_spec) |> add_recipe(quad_recipe) |> fit(train_data)
  Y3 <- workflow() |> add_model(lstSqrs_spec) |> add_recipe(cubic_recipe) |> fit(train_data)
  Y4 <- workflow() |> add_model(lstSqrs_spec) |> add_recipe(quart_recipe) |> fit(train_data)
 
  data.frame(model = c("linear", "quadratic", "cubic", "quartic"),
             rmse = c(retrieve_test_error(Y1, test_data), 
                   retrieve_test_error(Y2, test_data), 
                   retrieve_test_error(Y3, test_data), 
                   retrieve_test_error(Y4, test_data)),
             i = i) |>
    rbind(test_errors) -> test_errors

}
test_errors |> 
  group_by(model) |>
  summarise(rmse = sqrt(mean(rmse))) |>
  kable()

```

```{r}
ggplot(exploratory_df) +
  geom_point(aes(x = mean_pH,
                 y = mean_Temp))
```
```{r}
RWAR_dosing_lag_incdec <- read_csv("RWAR_dosing_lag_incdec.csv")
head(RWAR_dosing_lag_incdec)

```
```{r}
RWAR_dosing_lag_incdec <- RWAR_dosing_lag_incdec %>%
  select(-c(FeCl_change, Polymer_change))
head(RWAR_dosing_lag_incdec)
```


```{r}
library(mgcv)
library(parsnip)
df_full <- RWAR_dosing_lag_incdec
df_train <- df_full |> filter(year(Timestamp) <= 2019)
df_test  <- df_full |> filter(year(Timestamp) == 2020)

gam_spec <- gen_additive_mod() |> 
  set_engine("mgcv") |> 
  set_mode("regression")
gam_rec <- recipe(FeCl_dose ~ Polymer_dose + mean_Temp + mean_pH + mean_Conductivity +
                 mean_Turbidity + Temp_lag1 + Temp_lag2 +
                 pH_lag1 + pH_lag2 + Cond_lag1 + Cond_lag2 +
                 Turb_lag1 + Turb_lag2, data = df_train)

gam_wf <- workflow() |>
  add_model(gam_spec) |>
  add_recipe(gam_rec)

gam_fit <- gam(
  FeCl_dose ~ s(Polymer_dose) + s(mean_Temp) + s(mean_pH) + s(mean_Conductivity) +
               s(mean_Turbidity) + s(Temp_lag1) + s(Temp_lag2) +
               s(pH_lag1) + s(pH_lag2) + s(Cond_lag1) + s(Cond_lag2) +
               s(Turb_lag1) + s(Turb_lag2),
  data = df_train
)

gam_fit |> tidy()
gam_fit |> glance()
```
```{r}
pred_df <- df_test %>% 
  mutate(pred = predict(gam_fit, newdata = df_test))
rmse(pred_df, truth = FeCl_dose, estimate = pred)
#The test data shows that 

```

```{r}

dat_grid_dose <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(Polymer_dose = seq(min(df_train$Polymer_dose),
                                      max(df_train$Polymer_dose),
                                      length.out = 100))
dat_grid_temp <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(mean_Temp = seq(min(df_train$mean_Temp), 
                         max(df_train$mean_Temp),
                                      length.out = 100))
dat_grid_pH <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(mean_pH = seq(min(df_train$mean_pH), max(df_train$mean_pH),
                                      length.out = 100))
dat_grid_cond <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(mean_Conductivity = seq(min(df_train$mean_Conductivity), max(df_train$mean_Conductivity),
                                      length.out = 100))
dat_grid_turb <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(mean_Turbidity = seq(min(df_train$mean_Turbidity), max(df_train$mean_Turbidity),
                                      length.out = 100))
dat_grid_temp_lag1 <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(Temp_lag1 = seq(min(df_train$Temp_lag1), max(df_train$Temp_lag1),
                                      length.out = 100))
dat_grid_temp_lag2 <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(Temp_lag2 = seq(min(df_train$Temp_lag2), max(df_train$Temp_lag2),
                                      length.out = 100))
dat_grid_pH_lag1 <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(pH_lag1 = seq(min(df_train$pH_lag1), max(df_train$pH_lag1),
                                      length.out = 100))
dat_grid_pH_lag2 <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(pH_lag2 = seq(min(df_train$pH_lag2), max(df_train$pH_lag2),
                                      length.out = 100))
dat_grid_cond_lag1 <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(Cond_lag1 = seq(min(df_train$Cond_lag1), max(df_train$Cond_lag1),
                                      length.out = 100))
dat_grid_cond_lag2 <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(Cond_lag2 = seq(min(df_train$Cond_lag2), max(df_train$Cond_lag2),
                                      length.out = 100))
dat_grid_turb_lag1 <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(Turb_lag1 = seq(min(df_train$Turb_lag1), max(df_train$Turb_lag1),
                                      length.out = 100))
dat_grid_turb_lag2 <- df_train |> 
  summarize(
    across(everything(), mean, na.rm = TRUE)
  ) |> 
  slice(rep(1, 100)) |> 
  mutate(Turb_lag2 = seq(min(df_train$Turb_lag2), max(df_train$Turb_lag2),
                                      length.out = 100))

pred1 <- predict(gam_fit, newdata = dat_grid_dose, type = "response", se.fit = TRUE)
dose_pred <- dat_grid_dose |> mutate(
  .fitted = pred1$fit,
  .lower = pred1$fit - 2 * pred1$se.fit,
  .upper = pred1$fit + 2 * pred1$se.fit
  )
pred2 <- predict(gam_fit, newdata = dat_grid_temp, type = "response", se.fit = TRUE)
temp_pred <- dat_grid_temp |> mutate(
  .fitted = pred2$fit,
  .lower = pred2$fit - 2 * pred2$se.fit,
  .upper = pred2$fit + 2 * pred2$se.fit
)
pred3 <- predict(gam_fit, newdata = dat_grid_pH, type = "response", se.fit = TRUE)
pH_pred <- dat_grid_pH |> mutate(
  .fitted = pred3$fit,
  .lower = pred3$fit - 2 * pred3$se.fit,
  .upper = pred3$fit + 2 * pred3$se.fit
)
pred4 <- predict(gam_fit, newdata = dat_grid_cond, type = "response", se.fit = TRUE)
cond_pred <- dat_grid_cond |> mutate(
  .fitted = pred4$fit,
  .lower = pred4$fit - 2 * pred4$se.fit,
  .upper = pred4$fit + 2 * pred4$se.fit
)
pred5 <- predict(gam_fit, newdata = dat_grid_turb, type = "response", se.fit = TRUE)
turb_pred <- dat_grid_turb |> mutate(
  .fitted = pred5$fit,
  .lower = pred5$fit - 2 * pred5$se.fit,
  .upper = pred5$fit + 2 * pred5$se.fit
)
pred6 <- predict(gam_fit, newdata = dat_grid_temp_lag1, type = "response", se.fit = TRUE)
tempLag1_pred <- dat_grid_temp_lag1 |> mutate(
  .fitted = pred6$fit,
  .lower = pred6$fit - 2 * pred6$se.fit,
  .upper = pred6$fit + 2 * pred6$se.fit
)
pred7 <- predict(gam_fit, newdata = dat_grid_temp_lag2, type = "response", se.fit = TRUE)
tempLag2_pred <- dat_grid_temp_lag2 |> mutate(
  .fitted = pred7$fit,
  .lower = pred7$fit - 2 * pred7$se.fit,
  .upper = pred7$fit + 2 * pred7$se.fit
)
pred8 <- predict(gam_fit, newdata = dat_grid_pH_lag1, type = "response", se.fit = TRUE)
pHLag1_pred <- dat_grid_pH_lag1 |> mutate(
  .fitted = pred8$fit,
  .lower = pred8$fit - 2 * pred8$se.fit,
  .upper = pred8$fit + 2 * pred8$se.fit
)
pred9 <- predict(gam_fit, newdata = dat_grid_pH_lag2, type = "response", se.fit = TRUE)
pHLag2_pred <- dat_grid_pH_lag2 |> mutate(
  .fitted = pred9$fit,
  .lower = pred9$fit - 2 * pred9$se.fit,
  .upper = pred9$fit + 2 * pred9$se.fit
)
pred10 <- predict(gam_fit, newdata = dat_grid_cond_lag1, type = "response", se.fit = TRUE)
condLag1_pred <- dat_grid_cond_lag1 |> mutate(
  .fitted = pred10$fit,
  .lower = pred10$fit - 2 * pred10$se.fit,
  .upper = pred10$fit + 2 * pred10$se.fit
)
pred11 <- predict(gam_fit, newdata = dat_grid_cond_lag2, type = "response", se.fit = TRUE)
condLag2_pred <- dat_grid_cond_lag2 |> mutate(
  .fitted = pred11$fit,
  .lower = pred11$fit - 2 * pred11$se.fit,
  .upper = pred11$fit + 2 * pred11$se.fit
)
pred12 <- predict(gam_fit, newdata = dat_grid_turb_lag1, type = "response", se.fit = TRUE)
turbLag1_pred <- dat_grid_turb_lag1 |> mutate(
  .fitted = pred12$fit,
  .lower = pred12$fit - 2 * pred12$se.fit,
  .upper = pred12$fit + 2 * pred12$se.fit
)
pred13 <- predict(gam_fit, newdata = dat_grid_turb_lag2, type = "response", se.fit = TRUE)
turbLag2_pred <- dat_grid_turb_lag2 |> mutate(
  .fitted = pred13$fit,
  .lower = pred13$fit - 2 * pred13$se.fit,
  .upper = pred13$fit + 2 * pred13$se.fit
)

```

```{r}
summary(gam_fit)
```


```{r}
ggplot(pred_df) +
  geom_point(aes(x = FeCl_dose, y = pred), alpha = 0.3) +
  geom_abline(slope = 1, 
              intercept = coef(gam_fit)[1],
              color = 'red',
              lwd = 1)
  
```
```{r}
ggplot(df_test) +
  geom_line(aes(y = FeCl_dose), color = 'orange')

```

The GAM model shows poor performance when making prediction of the dose requirements for water treatment.





